FosGrupo:
  type: entity
  table: fos_grupo
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
    roles:
      type: array
      nullable: false
  manyToMany:
    user:
      targetEntity: Usuario
      cascade: {  }
      mappedBy: group
      inversedBy: null
      joinTable: null
      orderBy: null
  lifecycleCallbacks: {  }
