TipoFuncionario:
  type: entity
  table: tipo_funcionario
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    nombre:
      type: string
      length: 45
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
