cargos:
    pattern:  /
    defaults: { _controller: "GobernacionRrhhBundle:Cargos:index" }

cargos_show:
    pattern:  /{id}/show
    defaults: { _controller: "GobernacionRrhhBundle:Cargos:show" }

cargos_new:
    pattern:  /new
    defaults: { _controller: "GobernacionRrhhBundle:Cargos:new" }

cargos_create:
    pattern:  /create
    defaults: { _controller: "GobernacionRrhhBundle:Cargos:create" }
    requirements: { _method: post }

cargos_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "GobernacionRrhhBundle:Cargos:edit" }

cargos_update:
    pattern:  /{id}/update
    defaults: { _controller: "GobernacionRrhhBundle:Cargos:update" }
    requirements: { _method: post }

cargos_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "GobernacionRrhhBundle:Cargos:delete" }
    requirements: { _method: post }
