titulos:
    pattern:  /
    defaults: { _controller: "GobernacionRrhhBundle:Titulos:index" }

titulos_show:
    pattern:  /{id}/show
    defaults: { _controller: "GobernacionRrhhBundle:Titulos:show" }

titulos_new:
    pattern:  /new
    defaults: { _controller: "GobernacionRrhhBundle:Titulos:new" }

titulos_create:
    pattern:  /create
    defaults: { _controller: "GobernacionRrhhBundle:Titulos:create" }
    requirements: { _method: post }

titulos_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "GobernacionRrhhBundle:Titulos:edit" }

titulos_update:
    pattern:  /{id}/update
    defaults: { _controller: "GobernacionRrhhBundle:Titulos:update" }
    requirements: { _method: post }

titulos_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "GobernacionRrhhBundle:Titulos:delete" }
    requirements: { _method: post }
