GobernacionRrhhBundle_homepage:
    pattern:  /
    defaults: { _controller: GobernacionRrhhBundle:Rrhh:index }

GobernacionRrhhBundle_dep:
    resource: "@GobernacionRrhhBundle/Resources/config/routing/dependencia.yml"
    prefix:   /dep

GobernacionRrhhBundle_dir:
    resource: "@GobernacionRrhhBundle/Resources/config/routing/direccion.yml"
    prefix:   /dir

GobernacionRrhhBundle_cargos:
    resource: "@GobernacionRrhhBundle/Resources/config/routing/cargos.yml"
    prefix:   /cargos
    
GobernacionRrhhBundle_permiso:
    resource: "@GobernacionRrhhBundle/Resources/config/routing/permiso.yml"
    prefix:   /permiso
