GobernacionRrhhBundle_homepage:
    pattern:  /
    defaults: { _controller: GobernacionRrhhBundle:Rrhh:index }

GobernacionRrhhBundle_dep:
    resource: "@GobernacionRrhhBundle/Resources/config/routing/dependencia.yml"
    prefix:   /dep

GobernacionRrhhBundle_dir:
    resource: "@GobernacionRrhhBundle/Resources/config/routing/direccion.yml"
    prefix:   /dir
    
GobernacionRrhhBundle_funcionario:
    resource: "@GobernacionRrhhBundle/Resources/config/routing/funcionario.yml"
    prefix:   /funcionario